/* Chinese learning deck — TOCFL-aligned, traditional+simplified, bopomofo+pinyin, example sentences.
   t=traditional s=simplified b=bopomofo p=pinyin m=meaning n=note eg=example (zh|pinyin|en) */
window.CURRICULUM = [
{ id:"foundation", badge:"FOUNDATION", title:"Bopomofo & Tones", sub:"the sound system first", lessons:[
  { id:"f1", icon:"🎵", title:"The 4 tones", cards:[
    {t:"媽",s:"妈",b:"ㄇㄚ",p:"mā",m:"mother (tone 1 – flat/high)",n:"Hold one high steady note."},
    {t:"麻",s:"麻",b:"ㄇㄚˊ",p:"má",m:"hemp (tone 2 – rising)",n:"Rise like asking 'huh?'"},
    {t:"馬",s:"马",b:"ㄇㄚˇ",p:"mǎ",m:"horse (tone 3 – dip)",n:"Down then up, like a valley."},
    {t:"罵",s:"骂",b:"ㄇㄚˋ",p:"mà",m:"to scold (tone 4 – fall)",n:"Sharp drop, like a firm 'No!'"},
    {t:"嗎",s:"吗",b:"ㄇㄚ˙",p:"ma",m:"(question word, neutral)",n:"Quick & light. 好嗎? = okay?"},
  ]},
  { id:"f2", icon:"👅", title:"Tricky sounds (x q j)", cards:[
    {t:"西",s:"西",b:"ㄒㄧ",p:"xī",m:"west",n:"ㄒ: tongue forward, smile-shape. Not English 'x'."},
    {t:"七",s:"七",b:"ㄑㄧ",p:"qī",m:"seven",n:"ㄑ: light 'ch', forward. Not 'kw'."},
    {t:"家",s:"家",b:"ㄐㄧㄚ",p:"jiā",m:"home / family",n:"ㄐ: soft 'j', tongue forward."},
    {t:"小",s:"小",b:"ㄒㄧㄠˇ",p:"xiǎo",m:"small",n:""},
    {t:"請",s:"请",b:"ㄑㄧㄥˇ",p:"qǐng",m:"please",n:""},
  ]},
  { id:"f3", icon:"🌀", title:"Retroflex (zh ch sh r)", cards:[
    {t:"吃",s:"吃",b:"ㄔ",p:"chī",m:"to eat",n:"ㄔ: tongue curled back.",eg:"我吃飯|wǒ chī fàn|I eat (a meal)"},
    {t:"是",s:"是",b:"ㄕˋ",p:"shì",m:"to be / yes",n:"ㄕ: curled back. NOT 'she'."},
    {t:"這",s:"这",b:"ㄓㄜˋ",p:"zhè",m:"this",n:"ㄓ: curled back."},
    {t:"人",s:"人",b:"ㄖㄣˊ",p:"rén",m:"person",n:"ㄖ: curled back, buzzy."},
    {t:"日",s:"日",b:"ㄖˋ",p:"rì",m:"day / sun",n:"日本 = Japan."},
  ]},
]},
{ id:"novice1", badge:"NOVICE 1", title:"First Words", sub:"greetings, courtesy, numbers", lessons:[
  { id:"n1a", icon:"👋", title:"Greetings", cards:[
    {t:"你好",s:"你好",b:"ㄋㄧˇ ㄏㄠˇ",p:"nǐ hǎo",m:"hello",n:"Two 3rd tones → first becomes 2nd.",eg:"你好嗎?|nǐ hǎo ma?|How are you?"},
    {t:"早安",s:"早安",b:"ㄗㄠˇ ㄢ",p:"zǎo'ān",m:"good morning",n:""},
    {t:"再見",s:"再见",b:"ㄗㄞˋ ㄐㄧㄢˋ",p:"zàijiàn",m:"goodbye",n:""},
    {t:"謝謝",s:"谢谢",b:"ㄒㄧㄝˋ ㄒㄧㄝ",p:"xièxie",m:"thank you",n:"",eg:"謝謝你|xièxie nǐ|Thank you"},
    {t:"不客氣",s:"不客气",b:"ㄅㄨˊ ㄎㄜˋ ㄑㄧˋ",p:"búkèqì",m:"you're welcome",n:""},
    {t:"對不起",s:"对不起",b:"ㄉㄨㄟˋ ㄅㄨˋ ㄑㄧˇ",p:"duìbùqǐ",m:"sorry",n:""},
    {t:"沒關係",s:"没关系",b:"ㄇㄟˊ ㄍㄨㄢ ㄒㄧ",p:"méiguānxi",m:"it's okay",n:""},
    {t:"請問",s:"请问",b:"ㄑㄧㄥˇ ㄨㄣˋ",p:"qǐngwèn",m:"excuse me (may I ask)",n:""},
  ]},
  { id:"n1b", icon:"🙋", title:"You, me, yes, no", cards:[
    {t:"我",s:"我",b:"ㄨㄛˇ",p:"wǒ",m:"I / me",n:"",eg:"我是學生|wǒ shì xuéshēng|I am a student"},
    {t:"你",s:"你",b:"ㄋㄧˇ",p:"nǐ",m:"you",n:""},
    {t:"他",s:"他",b:"ㄊㄚ",p:"tā",m:"he / him",n:""},
    {t:"她",s:"她",b:"ㄊㄚ",p:"tā",m:"she / her",n:"Same sound as 他, different character."},
    {t:"是",s:"是",b:"ㄕˋ",p:"shì",m:"to be / yes",n:""},
    {t:"不",s:"不",b:"ㄅㄨˋ",p:"bù",m:"not / no",n:"",eg:"我不是|wǒ búshì|I'm not"},
    {t:"好",s:"好",b:"ㄏㄠˇ",p:"hǎo",m:"good / okay",n:""},
    {t:"很",s:"很",b:"ㄏㄣˇ",p:"hěn",m:"very",n:"",eg:"很好|hěn hǎo|very good"},
  ]},
  { id:"n1c", icon:"🔢", title:"Numbers 1–10", cards:[
    {t:"一",s:"一",b:"ㄧ",p:"yī",m:"one",n:""},
    {t:"二",s:"二",b:"ㄦˋ",p:"èr",m:"two",n:"兩 (liǎng) before measure words."},
    {t:"三",s:"三",b:"ㄙㄢ",p:"sān",m:"three",n:""},
    {t:"四",s:"四",b:"ㄙˋ",p:"sì",m:"four",n:""},
    {t:"五",s:"五",b:"ㄨˇ",p:"wǔ",m:"five",n:""},
    {t:"六",s:"六",b:"ㄌㄧㄡˋ",p:"liù",m:"six",n:""},
    {t:"七",s:"七",b:"ㄑㄧ",p:"qī",m:"seven",n:""},
    {t:"八",s:"八",b:"ㄅㄚ",p:"bā",m:"eight",n:""},
    {t:"九",s:"九",b:"ㄐㄧㄡˇ",p:"jiǔ",m:"nine",n:""},
    {t:"十",s:"十",b:"ㄕˊ",p:"shí",m:"ten",n:"",eg:"十五|shíwǔ|fifteen"},
  ]},
]},
{ id:"novice2", badge:"NOVICE 2", title:"Daily Survival", sub:"shops, food, getting around", lessons:[
  { id:"n2a", icon:"🏪", title:"At the shop / 7-Eleven", cards:[
    {t:"多少錢",s:"多少钱",b:"ㄉㄨㄛ ㄕㄠˇ ㄑㄧㄢˊ",p:"duōshǎo qián",m:"how much?",n:"",eg:"這個多少錢?|zhège duōshǎo qián?|How much is this?"},
    {t:"這個",s:"这个",b:"ㄓㄜˋ ㄍㄜ˙",p:"zhège",m:"this one",n:"Point + say it."},
    {t:"那個",s:"那个",b:"ㄋㄚˋ ㄍㄜ˙",p:"nàge",m:"that one",n:""},
    {t:"要",s:"要",b:"ㄧㄠˋ",p:"yào",m:"want / will",n:"",eg:"我要這個|wǒ yào zhège|I want this one"},
    {t:"不要",s:"不要",b:"ㄅㄨˊ ㄧㄠˋ",p:"búyào",m:"don't want / no",n:"",eg:"袋子不要|dàizi búyào|No bag, thanks"},
    {t:"有",s:"有",b:"ㄧㄡˇ",p:"yǒu",m:"to have / there is",n:"",eg:"有沒有?|yǒu méiyǒu?|Do you have it?"},
    {t:"袋子",s:"袋子",b:"ㄉㄞˋ ㄗ˙",p:"dàizi",m:"bag",n:""},
    {t:"錢",s:"钱",b:"ㄑㄧㄢˊ",p:"qián",m:"money",n:""},
  ]},
  { id:"n2b", icon:"🍜", title:"Food & eating", cards:[
    {t:"吃飯",s:"吃饭",b:"ㄔ ㄈㄢˋ",p:"chīfàn",m:"to eat (a meal)",n:""},
    {t:"好吃",s:"好吃",b:"ㄏㄠˇ ㄔ",p:"hǎochī",m:"delicious",n:"",eg:"很好吃|hěn hǎochī|Very delicious"},
    {t:"水",s:"水",b:"ㄕㄨㄟˇ",p:"shuǐ",m:"water",n:""},
    {t:"茶",s:"茶",b:"ㄔㄚˊ",p:"chá",m:"tea",n:""},
    {t:"飯",s:"饭",b:"ㄈㄢˋ",p:"fàn",m:"rice / meal",n:""},
    {t:"麵",s:"面",b:"ㄇㄧㄢˋ",p:"miàn",m:"noodles",n:""},
    {t:"辣",s:"辣",b:"ㄌㄚˋ",p:"là",m:"spicy",n:"",eg:"不要辣|búyào là|Not spicy"},
    {t:"外帶",s:"外带",b:"ㄨㄞˋ ㄉㄞˋ",p:"wàidài",m:"takeout",n:"vs 內用 nèiyòng = dine in."},
  ]},
  { id:"n2c", icon:"🚇", title:"Getting around Taipei", cards:[
    {t:"在哪裡",s:"在哪里",b:"ㄗㄞˋ ㄋㄚˇ ㄌㄧˇ",p:"zài nǎlǐ",m:"where is it?",n:"",eg:"捷運在哪裡?|jiéyùn zài nǎlǐ?|Where's the MRT?"},
    {t:"捷運",s:"捷运",b:"ㄐㄧㄝˊ ㄩㄣˋ",p:"jiéyùn",m:"MRT (metro)",n:""},
    {t:"廁所",s:"厕所",b:"ㄘㄜˋ ㄙㄨㄛˇ",p:"cèsuǒ",m:"toilet",n:""},
    {t:"這裡",s:"这里",b:"ㄓㄜˋ ㄌㄧˇ",p:"zhèlǐ",m:"here",n:""},
    {t:"那裡",s:"那里",b:"ㄋㄚˋ ㄌㄧˇ",p:"nàlǐ",m:"there",n:""},
    {t:"左",s:"左",b:"ㄗㄨㄛˇ",p:"zuǒ",m:"left",n:""},
    {t:"右",s:"右",b:"ㄧㄡˋ",p:"yòu",m:"right",n:""},
    {t:"計程車",s:"出租车",b:"ㄐㄧˋ ㄔㄥˊ ㄔㄜ",p:"jìchéngchē",m:"taxi",n:"Taiwan term; mainland 出租车."},
  ]},
  { id:"n2d", icon:"⏰", title:"Time & days", cards:[
    {t:"今天",s:"今天",b:"ㄐㄧㄣ ㄊㄧㄢ",p:"jīntiān",m:"today",n:""},
    {t:"明天",s:"明天",b:"ㄇㄧㄥˊ ㄊㄧㄢ",p:"míngtiān",m:"tomorrow",n:""},
    {t:"昨天",s:"昨天",b:"ㄗㄨㄛˊ ㄊㄧㄢ",p:"zuótiān",m:"yesterday",n:""},
    {t:"現在",s:"现在",b:"ㄒㄧㄢˋ ㄗㄞˋ",p:"xiànzài",m:"now",n:"",eg:"現在幾點?|xiànzài jǐ diǎn?|What time is it now?"},
    {t:"點",s:"点",b:"ㄉㄧㄢˇ",p:"diǎn",m:"o'clock / dot",n:""},
    {t:"星期",s:"星期",b:"ㄒㄧㄥ ㄑㄧ",p:"xīngqí",m:"week",n:"星期一 = Monday."},
    {t:"分鐘",s:"分钟",b:"ㄈㄣ ㄓㄨㄥ",p:"fēnzhōng",m:"minute",n:""},
  ]},
]},
{ id:"home", badge:"NOVICE 2", title:"Family & Home", sub:"your daily life", lessons:[
  { id:"h1", icon:"👨‍👩‍👧", title:"Family", cards:[
    {t:"爸爸",s:"爸爸",b:"ㄅㄚˋ ㄅㄚ˙",p:"bàba",m:"dad (that's you!)",n:""},
    {t:"媽媽",s:"妈妈",b:"ㄇㄚ ㄇㄚ˙",p:"māma",m:"mom",n:""},
    {t:"女兒",s:"女儿",b:"ㄋㄩˇ ㄦˊ",p:"nǚ'ér",m:"daughter",n:"ㄋㄩ uses ü — round lips, say 'ee'."},
    {t:"寶寶",s:"宝宝",b:"ㄅㄠˇ ㄅㄠ˙",p:"bǎobao",m:"baby",n:""},
    {t:"老婆",s:"老婆",b:"ㄌㄠˇ ㄆㄛˊ",p:"lǎopó",m:"wife (affectionate)",n:"太太 tàitai is formal."},
    {t:"家",s:"家",b:"ㄐㄧㄚ",p:"jiā",m:"home / family",n:"",eg:"回家|huíjiā|go home"},
  ]},
  { id:"h2", icon:"❤️", title:"Baby & home life", cards:[
    {t:"我愛你",s:"我爱你",b:"ㄨㄛˇ ㄞˋ ㄋㄧˇ",p:"wǒ ài nǐ",m:"I love you",n:""},
    {t:"睡覺",s:"睡觉",b:"ㄕㄨㄟˋ ㄐㄧㄠˋ",p:"shuìjiào",m:"to sleep",n:"",eg:"寶寶睡覺了|bǎobao shuìjiào le|The baby is sleeping"},
    {t:"哭",s:"哭",b:"ㄎㄨ",p:"kū",m:"to cry",n:""},
    {t:"餓",s:"饿",b:"ㄜˋ",p:"è",m:"hungry",n:"",eg:"寶寶餓了|bǎobao è le|The baby is hungry"},
    {t:"尿布",s:"尿布",b:"ㄋㄧㄠˋ ㄅㄨˋ",p:"niàobù",m:"diaper",n:""},
    {t:"抱",s:"抱",b:"ㄅㄠˋ",p:"bào",m:"to hold / hug",n:"抱抱 = cuddle."},
    {t:"愛",s:"爱",b:"ㄞˋ",p:"ài",m:"love",n:"Traditional 愛 keeps 心 (heart); simplified 爱 dropped it."},
  ]},
]},
];
